### ISSUE TITLE
Peer to peer code review 05.11.21

### ISSUE THREAD

**Issue by anuarshaidenov** [arnrdn/portfolio-bootstrap#3]
## The code looks good, but there are some suggestions to improve:
- Align the elements on the page using d-flex class may help
- Using Bootstrap breakpoints make it more responsive
- Add a CSS file to customize elements according to the template

**Comment by arnrdn** [comment]
Thank you! Will do!

**Comment by vic778** [comment]
- The code looks good. but there are some changes you should make.
